export const USER_LOGIN_STATUS =  "USER_LOGIN_STATUS"
export const USER_LOGIN_SAVE_DATA =  "USER_LOGIN_SAVE_DATA"
export const USER_EXIT_CLEAR_DATA =  "USER_EXIT_CLEAR_DATA"
export const USER_REGISTER_SAVE_DATA =  "USER_REGISTER_SAVE_DATA"
